Master:
  InstallPlugins:
    - kubernetes:1.13.5
    - workflow-job:2.24
    - workflow-aggregator:2.5
    - credentials-binding:1.17
    - git:3.9.1
    - google-oauth-plugin:0.6
    - google-source-plugin:0.3
    - google-login:1.4
    - hashicorp-vault-plugin:2.2.0
    - ghprb:1.42.0
  Cpu: "1"
  Memory: "3500Mi"
  JavaOpts: "-Xms3500m -Xmx3500m"
  ServiceType: ClusterIP
Agent:
  Enabled: true
  resources:
    requests:
      cpu: "500m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
Persistence:
  Size: 100Gi
NetworkPolicy:
  ApiVersion: networking.k8s.io/v1
rbac:
  install: true
  serviceAccountName: cd-jenkins
